# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        /:categories/:title/


# Setup
title:            coppers-j
tagline:          'A blog by James Copperthwaite'
description:      'A blog by <a href="twitter.com/coppers_j" target="_blank">James Copperthwaite</a> about projects I work on and things that interest me. gihub alias <a href="github.com/user/coppers-j" target="_blank">@coppers-j</a>.'
url:              http://coppers-h.github.io
baseurl:          /

author:
  name:           'James Copperthwaite'
  url:            https://twitter.com/coppers_j

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/coppers-j/coppers-j.github.io
